<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://www.joyspe.com/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/tos/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/privacy/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/campaign/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/contact/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/ka/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/sa/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/ta/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/na/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/ha/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/ma/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/ya/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/ra/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/dictionary/wa/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/info_list/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/signup/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/login/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/pass/pass_page</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/message_list/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/keep_list/</loc>
</url>
<url>
<loc>https://www.joyspe.com/user/settings/</loc>
</url>
<?php if(isset($banner_data) && $banner_data): ?>
<url>
<loc>https://www.joyspe.com/campaign/travel_expense</loc>
</url>
<?php endif; ?>
<?php if (isset($banner_bonus_req) && $banner_bonus_req) : ?>
<url>
<loc>https://www.joyspe.com/campaign/trial_work</loc>
</url>
<?php endif; ?>
</urlset>